name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Update local toolchain
      run: |
          rustup update
          rustup component add clippy
          rustup install nightly

    - name: Toolchain info
      run: |
          cargo --version --verbose
          rustc --version
          cargo clippy --version
          cargo fmt --version

    - name: Lint
      run: |
          cargo fmt -- --check
          cargo clippy -- -D warnings

    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
